### ISSUE TITLE
SCSS syntax error when importing SCSS in js while using stub mode

### ISSUE THREAD

**Issue by jd-solanki** [unjs/unbuild#186]
### Environment

  System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 31.45 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 16.1

### Reproduction

Anu UI Lib: https://github.com/jd-solanki/anu

Steps:
1. clone the repo
2. Uncomment line 8 that imports SCSS file in `packages/preset-theme-default/src/index.ts`
3. run `pnpm install`
4. run project using `pnpm run dev` (let it generate dts files for 3 sec)
5. run docs using `pnpm run docs:dev`

Check the error on docs run.

### Describe the bug

> unbuild@1.0.2

I want to provide CSS file for my SCSS in dist using unbuild.

When I run the build using unbuild it successfully generates the CSS and the package is fine. However, the issue is its SCSS imports can't let docs run. It throws error: "SyntaxError: Invalid or unexpected token"

### Additional context

Discord post: https://discord.com/channels/473401852243869706/1050375232441036830

### Logs

```sh
/Users/jd/Projects/oss/anu/packages/preset-theme-default/src/scss/index.scss:1
@import '@unocss/reset/tailwind.css';
^

SyntaxError: Invalid or unexpected token
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at jiti (/Users/jd/Projects/oss/anu/node_modules/.pnpm/jiti@1.16.0/node_modules/jiti/dist/jiti.js:1:245552)
    at /Users/jd/Projects/oss/anu/packages/preset-theme-default/src/index.ts:8:1
    at jiti (/Users/jd/Projects/oss/anu/node_modules/.pnpm/jiti@1.16.0/node_modules/jiti/dist/jiti.js:1:247502)
    at /Users/jd/Projects/oss/anu/docs/uno.config.ts:9:14
    at jiti (/Users/jd/Projects/oss/anu/node_modules/.pnpm/jiti@1.16.0/node_modules/jiti/dist/jiti.js:1:247502)
    at loadConfigFile (/Users/jd/Projects/oss/anu/node_modules/.pnpm/unconfig@0.3.7/node_modules/unconfig/dist/index.cjs:155:11)
    at async Object.load (/Users/jd/Projects/oss/anu/node_modules/.pnpm/unconfig@0.3.7/node_modules/unconfig/dist/index.cjs:84:24)
    at async Object.loadConfig (/Users/jd/Projects/oss/anu/node_modules/.pnpm/@unocss+config@0.47.6/node_modules/@unocss/config/dist/index.cjs:50:18)
    at async reloadConfig (/Users/jd/Projects/oss/anu/node_modules/.pnpm/@unocss+vite@0.47.6/node_modules/@unocss/vite/dist/index.cjs:74:20)
/Users/jd/Projects/oss/anu/docs:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @anu-vue/documentation@1.0.0 dev: `vitepress dev`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.
```
```

**Comment by zoeyzhao19** [comment]
It seems that `unbuild` does not support CSS `@import`(stub with `JITI`, build with `rollup`),  maybe it is targeted at javascript bundler.  But you have worked it around by using mkdist builder.

**Comment by pi0** [comment]
Importing sass in sutub mode is not supported. Active watcher with custom rollup plugin might be best option once supported ~> #281
