### ISSUE TITLE
Type declaration generation fails

### ISSUE THREAD

**Issue by ayalon** [unjs/unbuild#21]
I try to build a nuxt module that uses some types of express in its interface.
Unfortunatly this throws an error. It seems, that rollup tries to access the types declaration files written in typescript as a CommonJs file.

I have created a full reproduction scenario:

https://github.com/dulnan/nuxt-graphql-middleware/tree/feature/refactor-build

How to reproduce
```
git clone -b feature/refactor-build git@github.com:dulnan/nuxt-graphql-middleware.git
npm install
npm run build / npx unbuild
```

The following error occurs:

```
Error building /nuxt2-app/modules/nuxt-graphql-middleware: SyntaxError: Unexpected token (17:8) in /nuxt2-app/modules/nuxt-graphql-middleware/node_modules/@types/express-serve-static-core/index.d.ts
SyntaxError: Unexpected token (17:8) in /nuxt2-app/modules/nuxt-graphql-middleware/node_modules/@types/express-serve-static-core/index.d.ts
    at Parser.pp$5.raise (file:///nuxt2-app/modules/nuxt-graphql-middleware/node_modules/rollup/dist/es/shared/rollup.js:19407:13)
    at Parser.pp.unexpected (file:///nuxt2-app/modules/nuxt-graphql-middleware/node_modules/rollup/dist/es/shared/rollup.js:16732:8)
    at Parser.pp.semicolon (file:///nuxt2-app/modules/nuxt-graphql-middleware/node_modules/rollup/dist/es/shared/rollup.js:16709:64)
    at Parser.pp$1.parseExpressionStatement (file:///nuxt2-app/modules/nuxt-graphql-middleware/node_modules/rollup/dist/es/shared/rollup.js:17192:8)
    at Parser.pp$1.parseStatement (file:///nuxt2-app/modules/nuxt-graphql-middleware/node_modules/rollup/dist/es/shared/rollup.js:16925:24)
    at Parser.pp$1.parseTopLevel (file:///nuxt2-app/modules/nuxt-graphql-middleware/node_modules/rollup/dist/es/shared/rollup.js:16789:21)
    at Parser.parse (file:///nuxt2-app/modules/nuxt-graphql-middleware/node_modules/rollup/dist/es/shared/rollup.js:16570:15)
    at Function.parse (file:///nuxt2-app/modules/nuxt-graphql-middleware/node_modules/rollup/dist/es/shared/rollup.js:16612:35)
    at Graph.contextParse (file:///nuxt2-app/modules/nuxt-graphql-middleware/node_modules/rollup/dist/es/shared/rollup.js:22658:38)
    at tryParse (/nuxt2-app/modules/nuxt-graphql-middleware/node_modules/@rollup/plugin-commonjs/dist/index.js:26:12) {
  pos: 834,
  loc: {
    column: 8,
    file: '/nuxt2-app/modules/nuxt-graphql-middleware/node_modules/@types/express-serve-static-core/index.d.ts',
    line: 17
  },
  raisedAt: 840,
  frame: '15: /// <reference types="node" />\n' +
    '16: \n' +
    '17: declare global {\n' +
    '            ^\n' +
    '18:     namespace Express {\n' +
    '19:         // These open interfaces may be extended in an application-specific manner via declaration merging.',
  id: '/nuxt2-app/modules/nuxt-graphql-middleware/node_modules/@types/express-serve-static-core/index.d.ts',
  hook: 'transform',
  code: 'PLUGIN_ERROR',
  plugin: 'commonjs',
  watchFiles: [
    '/nuxt2-app/modules/nuxt-graphql-middleware/src/module.ts',
    '/nuxt2-app/modules/nuxt-graphql-middleware/src/serverMiddleware.ts',
    '/nuxt2-app/modules/nuxt-graphql-middleware/src/codegen.ts',
    '/nuxt2-app/modules/nuxt-graphql-middleware/src/runtime/middlewarePlugin.ts',
    '/nuxt2-app/modules/nuxt-graphql-middleware/node_modules/@types/express-serve-static-core/index.d.ts'
  ]
}


```

**Comment by g1eny0ung** [comment]
Probably you need to mark this dep as an `external` dependency in `build.config.{js,ts,json}`.
