### ISSUE TITLE
Dependency "hookable" would cause error "TypeError: Cannot read properties of undefined (reading 'pkg')"

### ISSUE THREAD

**Issue by DevilTea** [unjs/unbuild#230]
### Environment

Node: 18
unbuild: 1.1.2

### Reproduction

https://github.com/DevilTea/repro-unbuild-issue

### Describe the bug

Run the build script would throw an exception
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/16652879/224368760-efd98181-5470-464f-a2b1-799935d52c9c.png">

After looking for the reason, I found that it is caused by the package "hookable" which just released version 5.5.0

hookable is in unbuild's dependencies and I found that its version is `^5.4.2` that would accept the minor update.

I've tested that install hookable with specific version like `5.4.2` everything would be okay, so it probably can say something that hookable updated breaks unbuild

### Logs

```sh
> repro-unbuild-issue@1.0.0 build /Users/deviltea/Documents/Programming/waa
> unbuild

Error building /Users/deviltea/Documents/Programming/waa: TypeError: Cannot read properties of undefined (reading 'pkg')
TypeError: Cannot read properties of undefined (reading 'pkg')
    at build:prepare (file:///Users/deviltea/Documents/Programming/waa/node_modules/.pnpm/unbuild@1.1.2/node_modules/unbuild/dist/shared/unbuild.e1e6feef.mjs:40:18)
    at file:///Users/deviltea/Documents/Programming/waa/node_modules/.pnpm/hookable@5.5.0/node_modules/hookable/dist/index.mjs:47:66
    at Object.run (file:///Users/deviltea/Documents/Programming/waa/node_modules/.pnpm/hookable@5.5.0/node_modules/hookable/dist/index.mjs:41:43)
    at file:///Users/deviltea/Documents/Programming/waa/node_modules/.pnpm/hookable@5.5.0/node_modules/hookable/dist/index.mjs:47:56
    at async build (file:///Users/deviltea/Documents/Programming/waa/node_modules/.pnpm/unbuild@1.1.2/node_modules/unbuild/dist/shared/unbuild.e1e6feef.mjs:934:3)
    at async main (file:///Users/deviltea/Documents/Programming/waa/node_modules/.pnpm/unbuild@1.1.2/node_modules/unbuild/dist/cli.mjs:35:3)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by DevilTea** [comment]
> There was a regression we shortly fixed with @danielroe. sorry for that.
> 
> Please use `npx nuxi@latest upgrade --force` to update hookable.

Toooooooooooo efficient!! Thx so much~
