### ISSUE TITLE
Failed to handle mixed ts/js project

### ISSUE THREAD

**Issue by trim21** [unjs/unbuild#250]
### Environment

node 18

unbuild 1.2.0

### Reproduction

```bash
git clone https://github.com/trim21/unbuild-bug-mixed-content
cd unbuild-bug-mixed-content
npm i
npx unbuild
```

### Describe the bug

I have a project with partial mixed ts and js files

the entry source file is js files,  but it import `.mts` file

and unbuild raise a error that it can't parse `.mts` file.

main.mjs ----> b.mts

### Logs

```sh
❯❯ ~\..\minio-js git:(unbuild-bug) npx unbuild
i Automatically detected entries: src/main/minio [esm] [cjs]                                               04:02:07
i Building minio                                                                                           04:02:07
Error building C:/Users/Trim21/proj/minio-js: RollupError: Unexpected token (Note that you need plugins to import files that are not JavaScript)
Error [RollupError]: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (file:///C:/Users/Trim21/proj/minio-js/node_modules/rollup/dist/es/shared/node-entry.js:2128:30)
    at Module.error (file:///C:/Users/Trim21/proj/minio-js/node_modules/rollup/dist/es/shared/node-entry.js:13322:16)
    at Module.tryParse (file:///C:/Users/Trim21/proj/minio-js/node_modules/rollup/dist/es/shared/node-entry.js:13999:25)
    at Module.setSource (file:///C:/Users/Trim21/proj/minio-js/node_modules/rollup/dist/es/shared/node-entry.js:13609:39)
    at ModuleLoader.addModuleSource (file:///C:/Users/Trim21/proj/minio-js/node_modules/rollup/dist/es/shared/node-entry.js:23574:20) {
  cause: SyntaxError: Unexpected token (22:21)
      at pp$4.raise (file:///C:/Users/Trim21/proj/minio-js/node_modules/rollup/dist/es/shared/node-entry.js:20978:13)
      at pp$9.unexpected (file:///C:/Users/Trim21/proj/minio-js/node_modules/rollup/dist/es/shared/node-entry.js:18279:8)
      at pp$9.expect (file:///C:/Users/Trim21/proj/minio-js/node_modules/rollup/dist/es/shared/node-entry.js:18273:26)
      at pp$7.parseBindingList (file:///C:/Users/Trim21/proj/minio-js/node_modules/rollup/dist/es/shared/node-entry.js:19545:17)
      at pp$5.parseMethod (file:///C:/Users/Trim21/proj/minio-js/node_modules/rollup/dist/es/shared/node-entry.js:20741:22)
      at pp$8.parseClassMethod (file:///C:/Users/Trim21/proj/minio-js/node_modules/rollup/dist/es/shared/node-entry.js:19034:35)
      at pp$8.parseClassElement (file:///C:/Users/Trim21/proj/minio-js/node_modules/rollup/dist/es/shared/node-entry.js:18992:10)
      at pp$8.parseClass (file:///C:/Users/Trim21/proj/minio-js/node_modules/rollup/dist/es/shared/node-entry.js:18910:24)
      at pp$8.parseStatement (file:///C:/Users/Trim21/proj/minio-js/node_modules/rollup/dist/es/shared/node-entry.js:18425:17)
      at Parser.parseExport (file:///C:/Users/Trim21/proj/minio-js/node_modules/rollup/dist/es/shared/node-entry.js:24889:33) {
    pos: 915,
    loc: Position { line: 22, column: 21 },
    raisedAt: 916
  },
  code: 'PARSE_ERROR',
  id: 'C:\\Users\\Trim21\\proj\\minio-js\\src\\main\\errors.mts',
  pos: 915,
  loc: {
    column: 21,
    file: 'C:\\Users\\Trim21\\proj\\minio-js\\src\\main\\errors.mts',
    line: 22
  },
  frame: '20: // APIs. NOTE: PresignedURL generation always requires access keys.\n' +
    '21: export class AnonymousRequestError extends ExtendableError {\n' +
    '22:   constructor(message: string) {\n' +
    '                         ^\n' +
    '23:     super(message)\n' +
    '24:   }',
  watchFiles: [
    'C:\\Users\\Trim21\\proj\\minio-js\\src\\main\\minio.mjs',
    'C:\\Users\\Trim21\\proj\\minio-js\\src\\main\\CredentialProvider.mjs',
    'C:\\Users\\Trim21\\proj\\minio-js\\src\\main\\extensions.mjs',
    'C:\\Users\\Trim21\\proj\\minio-js\\src\\main\\notification.mjs',
    'C:\\Users\\Trim21\\proj\\minio-js\\src\\main\\object-uploader.mjs',
    'C:\\Users\\Trim21\\proj\\minio-js\\src\\main\\transformers.mjs',
    'C:\\Users\\Trim21\\proj\\minio-js\\src\\main\\helpers.mjs',
    'C:\\Users\\Trim21\\proj\\minio-js\\src\\main\\xml-parsers.mjs',
    'C:\\Users\\Trim21\\proj\\minio-js\\src\\main\\errors.mts',
    'C:\\Users\\Trim21\\proj\\minio-js\\src\\main\\Credentials.mjs'
  ]
}
```

**Comment by gsennua** [comment]
Look's like your errors.mts is a typescript file format. Have you tried using .ts for typescript files extension and .js for javascript ? I assume unbuild is working with the extension type.

**Comment by trim21** [comment]
no I can't, I have to use mjs and mts so nodejs load these files run in esm scope

**Comment by gsennua** [comment]
no keep the .ts file and .js and unbuild will do the job for you. Unbuild parse the package.json file to know what to build and the ouput format. So at least if you want .mjs file you should add "type": "module" in your package.json. Why having typscript and javscript in the same repository ? I think you can also use the build.config to specify the output .mjs

**Comment by gsennua** [comment]
Yes it can't because you don't use standard extension type for your src files. I think you should use build.config to specify the type of your files to unbuild as unbuild think the parsed files are javascript.

**Comment by trim21** [comment]
> Yes it can't because you don't use standard extension type for your src files. I think you should use build.config to specify the type of your files to unbuild as unbuild think the parsed files are javascript or find a way that your test works with .ts .js extension.

`.mts` and `.cts` are supported TypeScript file extensions I think...

https://www.typescriptlang.org/docs/handbook/esm-node.html#new-file-extensions

**Comment by gsennua** [comment]
Yes but it's dist/ build file extension not src source file extension

**Comment by trim21** [comment]
> Yes but I assume it's dist/ build file extension not src source file extension

No, actually it's source file extension.

TS project should build/dist `.js`, `.mjs` or `.cjs` with `.d.ts`, TS project should not emit `ts` files.

**Comment by gsennua** [comment]
In any case, I think that it's because of the format that Unbuild doesn't understand that it's TypeScript. Have you tried testing by replacing it with .ts to see what happens?

**Comment by zoeyzhao19** [comment]
@trim21 , you can use `esbuild` option like
```js
import {defineBuildConfig} from 'unbuild'

export default defineBuildConfig({
  entries: ['./src/main/minio.mjs'],
  declaration: false,
  rollup: {
    esbuild: {
      loaders: {
        '.mts': "ts"
      }
    }
  }
})
```
Ideally, config above should have help you out of the error reported. But there is a related [issue](https://github.com/unjs/unbuild/issues/256) should be resolved first that custom esbuild options might break build.
