### ISSUE TITLE
unbuild throw "Top-level await is not available in the configured target environment ("es2020") " error

### ISSUE THREAD

**Issue by onepunchcat** [unjs/unbuild#257]
### Environment

Node: v18.16.0
unbuild: ^1.2.1

```json
// package.json
{
  "type": "module",
}
```

```json
// tsconfig.json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "nodenext",
    "allowImportingTsExtensions": true,
  }
}
```

```ts
// build.config.ts
export default defineBuildConfig({
  entries: ['./src/index'],
  declaration: true,
})
```

### Reproduction

https://codesandbox.io/p/sandbox/ecstatic-thunder-8e1g95

### Describe the bug

unbuild throw 'Top-level await is not available in the configured target environment ("es2020")'

### Logs

```sh
$ unbuild

ℹ Building vanilla-typescript                                       8:48:02 AM
Error building /project/sandbox: Error: Transform failed with 1 error:
/project/sandbox/src/index.ts:5:0: ERROR: Top-level await is not available in the configured target environment ("es2020")
Error: Transform failed with 1 error:
/project/sandbox/src/index.ts:5:0: ERROR: Top-level await is not available in the configured target environment ("es2020")
    at failureErrorWithLog (/project/sandbox/node_modules/esbuild/lib/main.js:1636:15)
    at /project/sandbox/node_modules/esbuild/lib/main.js:837:29
    at responseCallbacks.<computed> (/project/sandbox/node_modules/esbuild/lib/main.js:697:9)
    at handleIncomingPacket (/project/sandbox/node_modules/esbuild/lib/main.js:752:9)
    at Socket.readFromStdout (/project/sandbox/node_modules/esbuild/lib/main.js:673:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [],
      pluginName: '',
      text: 'Top-level await is not available in the configured target environment ("es2020")'
    }
  ],
  warnings: [],
  code: 'PLUGIN_ERROR',
  plugin: 'commonjs--resolver',
  hook: 'resolveId',
  id: '/project/sandbox/src/index.ts',
  watchFiles: [ '/project/sandbox/src/index.ts' ]
}
```
```

**Comment by sadeghbarati** [comment]
[Top-level await is a footgun 👣🔫](https://gist.github.com/Rich-Harris/0b6f317657f5167663b493c722647221)
https://v8.dev/features/top-level-await#isn%E2%80%99t-top-level-await-a-footgun%3F

Never saw top-level await in libraries but saw in Function scope/blocks

**Comment by zoeyzhao19** [comment]
`unbuild` does not read `tsconfig.json` configuration now ,  this is a temporary work around
```js
import { defineBuildConfig } from "unbuild";

export default defineBuildConfig({
  entries: ["./src/index"],
  declaration: true,
  rollup: {
    esbuild: {
      target: "esnext"
    }
  }
});

```
