### ISSUE TITLE
Excessive options passed to esbuild causing error

### ISSUE THREAD

**Issue by brendonmatos** [unjs/unbuild#291]
### Environment

➜ pnpm -v
8.5.0

➜ node -v 
v18.12.0

### Reproduction

https://stackblitz.com/edit/node-4y4mur?file=build.config.ts

`npm run build`

### Describe the bug

https://github.com/unjs/unbuild/blob/bfb95f5f1bca10902ab9734e2f6c4edf429a803a/src/builder/plugins/esbuild.ts#L22-L33

https://github.com/unjs/unbuild/blob/bfb95f5f1bca10902ab9734e2f6c4edf429a803a/src/builder/plugins/esbuild.ts#L74-L78

Doing that, passing the option `loaders` in plural will return an error from esbuild:

```
/Users/brendonferreira/Projects/brendon/bundlers-lab/node_modules/esbuild/lib/main.js:255:12: ERROR: Invalid option in transform() call: "loaders"
    at failureErrorWithLog (/Users/brendonferreira/Projects/brendon/bundlers-lab/node_modules/esbuild/lib/main.js:1636:15)
    at /Users/brendonferreira/Projects/brendon/bundlers-lab/node_modules/esbuild/lib/main.js:871:20
    at responseCallbacks.<computed> (/Users/brendonferreira/Projects/brendon/bundlers-lab/node_modules/esbuild/lib/main.js:697:9)
    at handleIncomingPacket (/Users/brendonferreira/Projects/brendon/bundlers-lab/node_modules/esbuild/lib/main.js:752:9)
    at Socket.readFromStdout (/Users/brendonferreira/Projects/brendon/bundlers-lab/node_modules/esbuild/lib/main.js:673:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) 
```

**Comment by pi0** [comment]
Hi. Thanks for reporting this. Testing locally, issue is fixed with [v2.0.0-rc.0](https://github.com/unjs/unbuild/releases/tag/v2.0.0-rc.0).

However i am getting an (unrelated) error from dts plugin, you can try to disable it for now.

**Comment by pi0** [comment]
Here is a working example with v2: https://stackblitz.com/edit/node-ojkymu?file=src%2Findex.ts

**Comment by pi0** [comment]
I think it should also be working out of the box. Made #293 to followup on this. 

Please ping me to reopen or new issue if you still have issues 👍🏼
