### ISSUE TITLE
`main` property definition is missing in `package.json`

### ISSUE THREAD

**Issue by deleonio** [unjs/unbuild#367]
### Environment

node

### Reproduction

use [knip](https://knip.dev/)

### Describe the bug

```bash
pnpm unused

> power-flow@0.0.0 unused /project
> knip

Analyzing workspace ....
Error loading /project/build.config.ts
Reason: No "exports" main defined in /project/node_modules/unbuild/package.json
 ELIFECYCLE  Command failed with exit code 2.
```

### Logs

```sh
In the `package.json` is missing, the `main` property definition.
```

**Comment by pi0** [comment]
Thanks for the issue. But at least for Node.js, this field is optional. So while it is something we can do to just fix knip, unless there is no reason to, I guess it is probably best that this tool fixes this.  (https://nodejs.org/api/packages.html#main-entry-point-export)

**Comment by tobiasdiez** [comment]
I also get what appears to be a similar error:
```
packages/nuxt-module build: Error trying import ./build.config from /Users/runner/work/storybook/storybook/packages/nuxt-module Error: No "exports" main defined in /Users/runner/work/storybook/storybook/node_modules/.pnpm/@nuxt+module-builder@0.8.1_@nuxt+kit@3.12.3_magicast@0.3.4_rollup@4.18.0__nuxi@3.12.0_sass@1.77.6_typescript@5.5.3/node_modules/unbuild/package.json
packages/nuxt-module build:     at new NodeError (node:internal/errors:405:5)
packages/nuxt-module build:     at exportsNotFound (node:internal/modules/esm/resolve:366:10)
packages/nuxt-module build:     at packageExportsResolve (node:internal/modules/esm/resolve:656:13)
packages/nuxt-module build:     at resolveExports (node:internal/modules/cjs/loader:590:36)
packages/nuxt-module build:     at Module._findPath (node:internal/modules/cjs/loader:664:31)
packages/nuxt-module build:     at Module._resolveFilename (node:internal/modules/cjs/loader:1126:27)
packages/nuxt-module build:     at Function.resolve (node:internal/modules/helpers:188:19)
packages/nuxt-module build:     at _resolve (/Users/runner/work/storybook/storybook/node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:241814)
packages/nuxt-module build:     at jiti (/Users/runner/work/storybook/storybook/node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:244531)
packages/nuxt-module build:     at /Users/runner/work/storybook/storybook/packages/nuxt-module/build.config.ts:1:178
packages/nuxt-module build:     at evalModule (/Users/runner/work/storybook/storybook/node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:247313)
packages/nuxt-module build:     at jiti (/Users/runner/work/storybook/storybook/node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:245241)
packages/nuxt-module build:     at tryRequire (file:///Users/runner/work/storybook/storybook/node_modules/.pnpm/unbuild@2.0.0_sass@1.77.6_typescript@5.5.3/node_modules/unbuild/dist/index.mjs:196:12)
packages/nuxt-module build:     at build (file:///Users/runner/work/storybook/storybook/node_modules/.pnpm/unbuild@2.0.0_sass@1.77.6_typescript@5.5.3/node_modules/unbuild/dist/index.mjs:940:24)
packages/nuxt-module build:     at Object.run (file:///Users/runner/work/storybook/storybook/node_modules/.pnpm/@nuxt+module-builder@0.8.1_@nuxt+kit@3.12.3_magicast@0.3.4_rollup@4.18.0__nuxi@3.12.0_sass@1.77.6_typescript@5.5.3/node_modules/@nuxt/module-builder/dist/chunks/build.mjs:43:11)
packages/nuxt-module build:     at async runCommand (file:///Users/runner/work/storybook/storybook/node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.mjs:316:16)
packages/nuxt-module build:     at async runCommand (file:///Users/runner/work/storybook/storybook/node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.mjs:307:11)
packages/nuxt-module build:     at async runMain (file:///Users/runner/work/storybook/storybook/node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.mjs:445:7) {
packages/nuxt-module build:   code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
packages/nuxt-module build: }
```
