### ISSUE TITLE
`Unexpected token` coming from Vite/rollup source code when building

### ISSUE THREAD

**Issue by victorgarciaesgi** [unjs/unbuild#38]
# *Steps to reproduce*

Repo: https://github.com/victorgarciaesgi/nuxt-typed-router/tree/next

`yarn && yarn build`

With a tsc build, everyting works. But with unbuild I keep getting this error. I don't know where I can find documention on this.
I followed this article: https://dev.to/baroshem/introduction-to-nuxt-3-modules-5h8o

# *Error*

```
Error building /Users/victorgarcia/Desktop/projects/nuxt-typed-router: Error: Unexpected token
Error: Unexpected token
    at error (file:///Users/victorgarcia/Desktop/projects/nuxt-typed-router/node_modules/rollup/dist/es/shared/rollup.js:10316:30)
    at Module.error (file:///Users/victorgarcia/Desktop/projects/nuxt-typed-router/node_modules/rollup/dist/es/shared/rollup.js:12235:16)
    at Module.tryParse (file:///Users/victorgarcia/Desktop/projects/nuxt-typed-router/node_modules/rollup/dist/es/shared/rollup.js:12638:25)
    at Module.setSource (file:///Users/victorgarcia/Desktop/projects/nuxt-typed-router/node_modules/rollup/dist/es/shared/rollup.js:12541:24)
    at ModuleLoader.addModuleSource (file:///Users/victorgarcia/Desktop/projects/nuxt-typed-router/node_modules/rollup/dist/es/shared/rollup.js:22019:20) {
  code: 'PARSE_ERROR',
  parserError: SyntaxError: Unexpected token (67381:69)
      at Parser.pp$4.raise (file:///Users/victorgarcia/Desktop/projects/nuxt-typed-router/node_modules/rollup/dist/es/shared/rollup.js:19418:13)
      at Parser.pp$9.unexpected (file:///Users/victorgarcia/Desktop/projects/nuxt-typed-router/node_modules/rollup/dist/es/shared/rollup.js:16733:8)
      at Parser.pp$9.expect (file:///Users/victorgarcia/Desktop/projects/nuxt-typed-router/node_modules/rollup/dist/es/shared/rollup.js:16727:26)
      at Parser.pp$5.parseObj (file:///Users/victorgarcia/Desktop/projects/nuxt-typed-router/node_modules/rollup/dist/es/shared/rollup.js:19030:12)
      at Parser.pp$5.parseExprAtom (file:///Users/victorgarcia/Desktop/projects/nuxt-typed-router/node_modules/rollup/dist/es/shared/rollup.js:18769:17)
      at Parser.pp$5.parseExprSubscripts (file:///Users/victorgarcia/Desktop/projects/nuxt-typed-router/node_modules/rollup/dist/es/shared/rollup.js:18585:19)
      at Parser.pp$5.parseMaybeUnary (file:///Users/victorgarcia/Desktop/projects/nuxt-typed-router/node_modules/rollup/dist/es/shared/rollup.js:18551:17)
      at Parser.pp$5.parseExprOps (file:///Users/victorgarcia/Desktop/projects/nuxt-typed-router/node_modules/rollup/dist/es/shared/rollup.js:18478:19)
      at Parser.pp$5.parseMaybeConditional (file:///Users/victorgarcia/Desktop/projects/nuxt-typed-router/node_modules/rollup/dist/es/shared/rollup.js:18461:19)
      at Parser.pp$5.parseMaybeAssign (file:///Users/victorgarcia/Desktop/projects/nuxt-typed-router/node_modules/rollup/dist/es/shared/rollup.js:18428:19) {
    pos: 2082160,
    loc: Position { line: 67381, column: 69 },
    raisedAt: 2082161
  },
  id: '/Users/victorgarcia/Desktop/projects/nuxt-typed-router/node_modules/vite/dist/node/chunks/dep-7817f5b4.js',
  pos: 2082160,
  loc: {
    column: 60,
    file: '/Users/victorgarcia/Desktop/projects/nuxt-typed-router/node_modules/vite/dist/node/chunks/dep-7817f5b4.js',
    line: 67313
  },
  frame: '67311: const pendingModules = new Map();\n' +
    '67312: const pendingImports = new Map();\n' +
    '67313: async function ssrLoadModule(url, server, context = { global }, urlStack = []) {\n' +
    '                                                                   ^\n' +
    '67314:     url = unwrapId$1(url);\n' +
    '67315:     // when we instantiate multiple dependency modules in parallel, they may',
  watchFiles: [
    '/Users/victorgarcia/Desktop/projects/nuxt-typed-router/src/module.ts',
    '/Users/victorgarcia/Desktop/projects/nuxt-typed-router/src/generators/nuxtHook.ts',
    '/Users/victorgarcia/Desktop/projects/nuxt-typed-router/src/exports/index.ts',
    '/Users/victorgarcia/Desktop/projects/nuxt-typed-router/node_modules/@nuxt/kit-edge/dist/index.mjs',
    '/Users/victorgarcia/Desktop/projects/nuxt-typed-router/src/generators/output.generator.ts',
    '/Users/victorgarcia/Desktop/projects/nuxt-typed-router/src/generators/main.generator.ts',
    '/Users/victorgarcia/Desktop/projects/nuxt-typed-router/src/exports/useTypedRouter.ts',
    '/Users/victorgarcia/Desktop/projects/nuxt-typed-router/src/exports/__declaration.ts',
    '/Users/victorgarcia/Desktop/projects/nuxt-typed-router/src/utils/index.ts',
    '/Users/victorgarcia/Desktop/projects/nuxt-typed-router/src/generators/output.templates.ts',
    '/Users/victorgarcia/Desktop/projects/nuxt-typed-router/node_modules/mlly/dist/index.mjs',
    '/Users/victorgarcia/Desktop/projects/nuxt-typed-router/node_modules/defu/dist/defu.mjs',
    '/Users/victorgarcia/Desktop/projects/nuxt-typed-router/node_modules/unctx/dist/index.mjs',
    '/Users/victorgarcia/Desktop/projects/nuxt-typed-router/node_modules/untyped/dist/untyped.mjs',
    '/Users/victorgarcia/Desktop/projects/nuxt-typed-router/node_modules/dotenv/lib/main.js',
    '/Users/victorgarcia/Desktop/projects/nuxt-typed-router/node_modules/pkg-types/dist/index.mjs',
    '/Users/victorgarcia/Desktop/projects/nuxt-typed-router/node_modules/scule/dist/index.mjs',
    '/Users/victorgarcia/Desktop/projects/nuxt-typed-router/src/utils/prettier.utils.ts',
    '/Users/victorgarcia/Desktop/projects/nuxt-typed-router/src/utils/chunks.utils.ts',
    '/Users/victorgarcia/Desktop/projects/nuxt-typed-router/src/utils/save.utils.ts',
    '/Users/victorgarcia/Desktop/projects/nuxt-typed-router/src/utils/parsing.utils.ts',
    '\x00commonjsHelpers.js',
    '\x00/Users/victorgarcia/Desktop/projects/nuxt-typed-router/node_modules/dotenv/lib/main.js?commonjs-exports',
    '\x00fs?commonjs-external',
    '\x00path?commonjs-external',
    ...etc
]
```

**Comment by jtsang4** [comment]
Meet the same error with latest version(0.6.7).

**Comment by pi0** [comment]
Hi. Indeed you should include used dependencies in either `dependencies` or `peerDependencies` or use `externals` in `build.config` to avoid them being bundled.
