### ISSUE TITLE
The vite project will report an error when packaging the library built using unbuild

### ISSUE THREAD

**Issue by skyline523** [unjs/unbuild#423]
### Environment

node v20.10.0
unbuild 2.0.0

### Reproduction

https://github.com/skyline523/utils
or
using npm install @xperia11@utils

### Describe the bug

I published the library, in other vue3+vite project using any module in this library. when i build project will build failed.

### Logs

```sh
error during build:
RollupError: node_modules/.pnpm/pkg-types@1.1.0/node_modules/pkg-types/dist/index.mjs (1:9): "statSync" is not exported by "__vite-browser-external", imported by "node_modules/.pnpm/pkg-types@1.1.0/node_modules/pkg-types/dist/index.mjs".
file: E:/personal/NeteaseCloudMusicWeb/node_modules/.pnpm/pkg-types@1.1.0/node_modules/pkg-types/dist/index.mjs:1:9
1: import { statSync, promises } from 'node:fs';
            ^
2: import { resolve, join, isAbsolute, dirname } from 'pathe';
3: import { resolvePath } from 'mlly';
    at getRollupError (file:///E:/personal/NeteaseCloudMusicWeb/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/es/shared/parseAst.js:392:41)
    at error (file:///E:/personal/NeteaseCloudMusicWeb/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/es/shared/parseAst.js:388:42)
    at Module.error (file:///E:/personal/NeteaseCloudMusicWeb/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/es/shared/node-entry.js:13688:16)
    at Module.traceVariable (file:///E:/personal/NeteaseCloudMusicWeb/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/es/shared/node-entry.js:14136:29)
    at ModuleScope.findVariable (file:///E:/personal/NeteaseCloudMusicWeb/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/es/shared/node-entry.js:11817:39)
    at ReturnValueScope.findVariable (file:///E:/personal/NeteaseCloudMusicWeb/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/es/shared/node-entry.js:6037:38)      
    at FunctionBodyScope.findVariable (file:///E:/personal/NeteaseCloudMusicWeb/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/es/shared/node-entry.js:6037:38)     
    at BlockScope.findVariable (file:///E:/personal/NeteaseCloudMusicWeb/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/es/shared/node-entry.js:6037:38)
    at Identifier.bind (file:///E:/personal/NeteaseCloudMusicWeb/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/es/shared/node-entry.js:7311:40)
    at CallExpression.bind (file:///E:/personal/NeteaseCloudMusicWeb/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/es/shared/node-entry.js:4753:23)
    at CallExpression.bind (file:///E:/personal/NeteaseCloudMusicWeb/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/es/shared/node-entry.js:8975:15)
    at MemberExpression.bind (file:///E:/personal/NeteaseCloudMusicWeb/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/es/shared/node-entry.js:4753:23)
    at MemberExpression.bind (file:///E:/personal/NeteaseCloudMusicWeb/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/es/shared/node-entry.js:8632:19)
    at CallExpression.bind (file:///E:/personal/NeteaseCloudMusicWeb/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/es/shared/node-entry.js:4753:23)
    at CallExpression.bind (file:///E:/personal/NeteaseCloudMusicWeb/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/es/shared/node-entry.js:8975:15)
    at IfStatement.bind (file:///E:/personal/NeteaseCloudMusicWeb/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/es/shared/node-entry.js:4753:23)
    at BlockStatement.bind (file:///E:/personal/NeteaseCloudMusicWeb/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/es/shared/node-entry.js:4749:28)
    at TryStatement.bind (file:///E:/personal/NeteaseCloudMusicWeb/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/es/shared/node-entry.js:4753:23)
    at BlockStatement.bind (file:///E:/personal/NeteaseCloudMusicWeb/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/es/shared/node-entry.js:4749:28)
    at ArrowFunctionExpression.bind (file:///E:/personal/NeteaseCloudMusicWeb/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/es/shared/node-entry.js:4753:23)       
    at Property.bind (file:///E:/personal/NeteaseCloudMusicWeb/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/es/shared/node-entry.js:4753:23)
    at ObjectExpression.bind (file:///E:/personal/NeteaseCloudMusicWeb/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/es/shared/node-entry.js:4749:28)
    at VariableDeclarator.bind (file:///E:/personal/NeteaseCloudMusicWeb/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/es/shared/node-entry.js:4753:23)
    at VariableDeclaration.bind (file:///E:/personal/NeteaseCloudMusicWeb/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/es/shared/node-entry.js:4749:28)
    at Program.bind (file:///E:/personal/NeteaseCloudMusicWeb/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/es/shared/node-entry.js:4749:28)
    at Module.bindReferences (file:///E:/personal/NeteaseCloudMusicWeb/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/es/shared/node-entry.js:13669:18)
    at Graph.sortModules (file:///E:/personal/NeteaseCloudMusicWeb/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/es/shared/node-entry.js:19899:20)
    at Graph.build (file:///E:/personal/NeteaseCloudMusicWeb/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/es/shared/node-entry.js:19803:14)
    at async file:///E:/personal/NeteaseCloudMusicWeb/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/es/shared/node-entry.js:20447:13
    at async catchUnfinishedHookActions (file:///E:/personal/NeteaseCloudMusicWeb/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/es/shared/node-entry.js:19956:16)  
    at async rollupInternal (file:///E:/personal/NeteaseCloudMusicWeb/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/es/shared/node-entry.js:20442:5)
    at async build (file:///E:/personal/NeteaseCloudMusicWeb/node_modules/.pnpm/vite@5.2.9_@types+node@20.12.7/node_modules/vite/dist/node/chunks/dep-_QLjGPdL.js:67451:18)    
    at async CAC.<anonymous> (file:///E:/personal/NeteaseCloudMusicWeb/node_modules/.pnpm/vite@5.2.9_@types+node@20.12.7/node_modules/vite/dist/node/cli.js:842:9)
```

**Comment by skyline523** [comment]
i found that problom: used and export unocss in package/unocss/index.ts. but i need this config use for vite app. how can i do?

**Comment by s3xysteak** [comment]
Use unocss as devDeps and external it.
