### ISSUE TITLE
import index.d.ts error, build error

### ISSUE THREAD

**Issue by seho-dev** [unjs/unbuild#59]
```
Error building /Users/seho/Desktop/openSource/sword-function-framework: SyntaxError: Unexpected token (1:7) in /Users/seho/Desktop/openSource/sword-function-framework/node_modules/.pnpm/@sword-code-practice+types@1.1.7/node_modules/@sword-code-practice/types/sword-backend-framework/index.d.ts
SyntaxError: Unexpected token (1:7) in /Users/seho/Desktop/openSource/sword-function-framework/node_modules/.pnpm/@sword-code-practice+types@1.1.7/node_modules/@sword-code-practice/types/sword-backend-framework/index.d.ts
    at Parser.pp$4.raise (file:///Users/seho/Desktop/openSource/sword-function-framework/node_modules/.pnpm/rollup@2.70.1/node_modules/rollup/dist/es/shared/rollup.js:19504:13)
    at Parser.pp$9.unexpected (file:///Users/seho/Desktop/openSource/sword-function-framework/node_modules/.pnpm/rollup@2.70.1/node_modules/rollup/dist/es/shared/rollup.js:16800:8)
    at Parser.pp$9.expect (file:///Users/seho/Desktop/openSource/sword-function-framework/node_modules/.pnpm/rollup@2.70.1/node_modules/rollup/dist/es/shared/rollup.js:16794:26)
    at Parser.pp$8.parseExportSpecifiers (file:///Users/seho/Desktop/openSource/sword-function-framework/node_modules/.pnpm/rollup@2.70.1/node_modules/rollup/dist/es/shared/rollup.js:17813:8)
    at Parser.pp$8.parseExport (file:///Users/seho/Desktop/openSource/sword-function-framework/node_modules/.pnpm/rollup@2.70.1/node_modules/rollup/dist/es/shared/rollup.js:17730:28)
    at Parser.pp$8.parseStatement (file:///Users/seho/Desktop/openSource/sword-function-framework/node_modules/.pnpm/rollup@2.70.1/node_modules/rollup/dist/es/shared/rollup.js:16976:74)
    at Parser.pp$8.parseTopLevel (file:///Users/seho/Desktop/openSource/sword-function-framework/node_modules/.pnpm/rollup@2.70.1/node_modules/rollup/dist/es/shared/rollup.js:16857:21)
    at Parser.parse (file:///Users/seho/Desktop/openSource/sword-function-framework/node_modules/.pnpm/rollup@2.70.1/node_modules/rollup/dist/es/shared/rollup.js:16630:15)
    at Function.parse (file:///Users/seho/Desktop/openSource/sword-function-framework/node_modules/.pnpm/rollup@2.70.1/node_modules/rollup/dist/es/shared/rollup.js:16680:35)
    at Graph.contextParse (file:///Users/seho/Desktop/openSource/sword-function-framework/node_modules/.pnpm/rollup@2.70.1/node_modules/rollup/dist/es/shared/rollup.js:22794:38) {
  pos: 7,
  loc: {
    column: 7,
    file: '/Users/seho/Desktop/openSource/sword-function-framework/node_modules/.pnpm/@sword-code-practice+types@1.1.7/node_modules/@sword-code-practice/types/sword-backend-framework/index.d.ts',
    line: 1
  },
  raisedAt: 16,
  frame: '1: export interface ContextData {\n' +
    '          ^\n' +
    '2:   query?: unknown;\n' +
    '3:   params?: unknown;',
  id: '/Users/seho/Desktop/openSource/sword-function-framework/node_modules/.pnpm/@sword-code-practice+types@1.1.7/node_modules/@sword-code-practice/types/sword-backend-framework/index.d.ts',
  hook: 'transform',
  code: 'PLUGIN_ERROR',
  plugin: 'commonjs',
  watchFiles: [
    '/Users/seho/Desktop/openSource/sword-function-framework/src/index.ts',
    '/Users/seho/Desktop/openSource/sword-function-framework/src/hooks/index.ts',
    '/Users/seho/Desktop/openSource/sword-function-framework/src/hooks/pipeline.ts',
    '/Users/seho/Desktop/openSource/sword-function-framework/src/hooks/instruct.ts',
    '/Users/seho/Desktop/openSource/sword-function-framework/src/hooks/api.ts',
    '/Users/seho/Desktop/openSource/sword-function-framework/src/hooks/app.ts',
    '/Users/seho/Desktop/openSource/sword-function-framework/src/hooks/plugin.ts',
    '/Users/seho/Desktop/openSource/sword-function-framework/src/core/pipeline.ts',
    '/Users/seho/Desktop/openSource/sword-function-framework/typings/pipeline.d.ts',
    '/Users/seho/Desktop/openSource/sword-function-framework/node_modules/.pnpm/@sword-code-practice+types@1.1.7/node_modules/@sword-code-practice/types/sword-backend-framework/index.d.ts'
  ]
}
```

I have a type file of index.d.ts that exports an interface, I want to use this interface in my program, but the package has this error, how can I fix it?

**Comment by 1018715564** [comment]
I just reproduced the same scene with the smallest demo, but unfortunately, it did not reproduce, and the packaging was successful. It's midnight in China, I can only give you an open source project I'm developing, the problem code is in the master branch, you just need to install it with pnpm and execute npx build to see the error, thank you very much 💗

https://github.com/swordCodePractice/sword-framework

**Comment by varlinor** [comment]
@seho-dev  so how did you solve this problem？ I just meet the same error when I import a custom util which is import axios，and when I build my package， the console shows：Unexpected token (2:7) in node_modules/.pnpm/axios@1.4.0/node_modules/axios/index.d.ts
